In [85]:
import numpy as np
import pandas as pd
from icecream import ic

In [86]:
X = np.genfromtxt("hw01_data_points.csv", delimiter = ",", dtype = str)
y = np.genfromtxt("hw01_class_labels.csv", delimiter = ",", dtype = int)

In [87]:
# STEP 3
# first 50000 data points should be included to train
# remaining 44727 data points should be included to test
# should return X_train, y_train, X_test, and y_test
def train_test_split(X, y):
    # your implementation starts below
    trainset_size = 50000
    X_train = X[:50000]
    X_test = X[50000:]

    y_train = y[:50000]
    y_test = y[50000:]
    # your implementation ends above
    return(X_train, y_train, X_test, y_test)

X_train, y_train, X_test, y_test = train_test_split(X, y)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(50000, 21)
(50000,)
(44727, 21)
(44727,)


In [88]:
X.shape

(94727, 21)

In [89]:
[i for i in range(1, 3)]

[1, 2]

In [90]:
# STEP 4
# assuming that there are K classes
# should return a numpy array with shape (K,)
def estimate_prior_probabilities(y):
    # your implementation starts below
    
    # Assume class numeration starts from 1
    K = max(y) # Number of classes
    size = y.shape[0] # Total size of set y
    class_priors = []

    for c in range(1, K): # From 1 to K-1
        class_priors.append(sum(y==c)/size)

    class_priors.append(1-sum(class_priors))
    
    # your implementation ends above
    return(class_priors)

class_priors = estimate_prior_probabilities(y_train)
print(class_priors)

[0.04466, 0.95534]


In [91]:
# STEP 5
# assuming that there are K classes and D features
# should return four numpy arrays with shape (K, D)
def estimate_nucleotide_probabilities(X, y):
    K = max(y)  # Number of classes (assuming y starts from 0)
    D = X.shape[1]  # Number of features
    
    pAcd = np.zeros((K, D))
    pCcd = np.zeros((K, D))
    pGcd = np.zeros((K, D))
    pTcd = np.zeros((K, D))
    
    for c in range(1, K+1):
        # Filter data by class
        X_c = X[y == c]
        ic(c)
        
        for d in range(D):
            feature_column = X_c[:, d]
            total_samples = len(feature_column)
            
            pAcd[c-1][d] = np.sum(feature_column == 'A') / total_samples
            pCcd[c-1][d] = np.sum(feature_column == 'C') / total_samples
            pGcd[c-1][d] = np.sum(feature_column == 'G') / total_samples
            pTcd[c-1][d] = np.sum(feature_column == 'T') / total_samples


         
    return pAcd, pCcd, pGcd, pTcd

pAcd, pCcd, pGcd, pTcd = estimate_nucleotide_probabilities(X_train, y_train)


ic| c: 1
ic| c: 2


In [92]:
print(pAcd)
print(pCcd)
print(pGcd)
print(pTcd)

[[0.18674429 0.17913121 0.1437528  0.13390058 0.11912226 0.11374832
  0.10523959 0.10076131 0.08687864 0.07613077 0.06941335 0.08687864
  0.10120914 0.09628303 0.08105687 0.07926556 0.23510972 0.05015674
  0.24540976 0.23734886 0.2539185 ]
 [0.26832332 0.27719974 0.2723219  0.25808613 0.28153328 0.27784872
  0.27219629 0.26087048 0.25488308 0.26618795 0.27385015 0.26955848
  0.28913266 0.28486193 0.27694852 0.25260117 0.27766031 0.24981682
  0.28335462 0.28025624 0.29279628]]
[[0.28616211 0.28526646 0.28571429 0.29422302 0.31168831 0.31751008
  0.31034483 0.31258397 0.29735781 0.28034035 0.30541872 0.31840573
  0.33811017 0.36945813 0.38916256 0.33990148 0.2955665  0.67845947
  0.14464845 0.21988356 0.2539185 ]
 [0.22821195 0.22961459 0.22318756 0.22536479 0.21688613 0.22747922
  0.22278979 0.22431804 0.24516926 0.22618125 0.20903553 0.21158959
  0.20369711 0.20145707 0.22607658 0.24527393 0.21198736 0.32248205
  0.22067536 0.24414345 0.210815  ]]
[[0.15718764 0.15002239 0.1518137  0.1

In [93]:
# STEP 6
# assuming that there are N data points and K classes
# should return a numpy array with shape (N, K)
def calculate_score_values(X, pAcd, pCcd, pGcd, pTcd, class_priors):
    # your implementation starts below
    K = max(y)  # Number of classes (assuming y starts from 0)
    N, D = X.shape  # Number of data entries, number of features

    # Init score with priors
    score_values = [np.log(x) for x in class_priors]
    score_values = np.tile(np.log(class_priors), (N, 1))

    #
    pXcd = {"A":pAcd, "C":pCcd, "G":pGcd, "T":pTcd}

    # # Add feature Likelihoods
    # for i, row in X:
    #     for d in row:
    #         np.log(pXcd[d][i])

    # Loop through each data point
    for i in range(N):
        # Loop through each class
        for j in range(K):
            # Loop through each feature (nucleotide in the sequence)
            for d in range(D):
                nucleotide = X[i][d]
                score_values[i, j] += np.log(pXcd[nucleotide][j, d])






    # your implementation ends above
    return(score_values)

scores_train = calculate_score_values(X_train, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_train)

scores_test = calculate_score_values(X_test, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_test)


[[-32.29602984 -28.67631805]
 [-35.36510932 -29.06687849]
 [-33.1594779  -28.50829296]
 ...
 [-37.17901126 -29.28659414]
 [-35.6365549  -29.75138901]
 [-28.72885394 -28.68471489]]
[[-31.88852108 -28.73182527]
 [-40.83809258 -29.40573888]
 [-30.6177392  -29.98270774]
 ...
 [-38.49757139 -28.9923932 ]
 [-24.40343148 -29.115305  ]
 [-37.58089652 -28.27846954]]


In [94]:
# STEP 7
# assuming that there are K classes
# should return a numpy array with shape (K, K)
def calculate_confusion_matrix(y_truth, scores):
    # your implementation starts below
    K = scores.shape[1]  # Number of classes
    N = len(y_truth)  # Number of data points
    
    # Initialize confusion matrix with zeros
    confusion_matrix = np.zeros((K, K))
    
    # Find the predicted class labels
    predicted_classes = np.argmax(scores, axis=1)
    
    # Populate the confusion matrix
    for n in range(N):
        true_class = y_truth[n]
        predicted_class = predicted_classes[n]
        confusion_matrix[true_class-1][predicted_class] += 1
    # your implementation ends above
    return(confusion_matrix.T)

confusion_train = calculate_confusion_matrix(y_train, scores_train)
print(confusion_train)

confusion_test = calculate_confusion_matrix(y_test, scores_test)
print(confusion_test)

[[ 1489.  1460.]
 [  744. 46307.]]
[[ 1314.  1300.]
 [  686. 41427.]]
